[package]
name = "arrow-format"
version = "0.3.0"
edition = "2018"
license = "Apache-2.0"
authors = ["Jorge C. Leitao <jorgecarleitao@gmail.com>"]
keywords = [ "arrow", "analytics" ]
description = "Unofficial flatbuffers and tonic code of Apache Arrow spec"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = { version = "=2.0.0", optional = true }

tonic = { version = "0.6.0", optional = true }
prost = { version = "0.9.0", optional = true }
prost-derive = { version = "0.9.0", optional = true }

[features]
default = []
full = ["ipc", "flight-data", "flight-service"]
flight-data = ["prost", "prost-derive"]
flight-service = ["flight-data", "tonic"]
ipc = ["flatbuffers"]
